"""initial_schema

Revision ID: 06e0c1a6dbd5
Revises: 
Create Date: 2026-03-06 19:55:54.248707+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06e0c1a6dbd5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('config',
    sa.Column('config_id', sa.Uuid(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('config_id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('sports',
    sa.Column('sport_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('sport_id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('sportsbooks',
    sa.Column('sportsbook_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('odds_format_default', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('sportsbook_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('competitions',
    sa.Column('competition_id', sa.Uuid(), nullable=False),
    sa.Column('sport_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('tier', sa.String(length=1), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sport_id'], ['sports.sport_id'], ),
    sa.PrimaryKeyConstraint('competition_id')
    )
    op.create_table('parlays',
    sa.Column('parlay_id', sa.Uuid(), nullable=False),
    sa.Column('sportsbook_id', sa.Uuid(), nullable=False),
    sa.Column('run_date', sa.Date(), nullable=False),
    sa.Column('type', sa.Enum('regular', 'bonus', name='parlay_type'), nullable=False),
    sa.Column('stake', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('odds_total', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('potential_return', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('actual_return', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('status', sa.Enum('pending', 'won', 'lost', name='parlay_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sportsbook_id'], ['sportsbooks.sportsbook_id'], ),
    sa.PrimaryKeyConstraint('parlay_id')
    )
    op.create_table('matches',
    sa.Column('match_id', sa.Uuid(), nullable=False),
    sa.Column('competition_id', sa.Uuid(), nullable=False),
    sa.Column('home_team', sa.String(length=200), nullable=False),
    sa.Column('away_team', sa.String(length=200), nullable=False),
    sa.Column('kickoff_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('scheduled', 'in_progress', 'finished', 'postponed', 'cancelled', name='match_status'), nullable=False),
    sa.Column('home_score', sa.Integer(), nullable=True),
    sa.Column('away_score', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['competition_id'], ['competitions.competition_id'], ),
    sa.PrimaryKeyConstraint('match_id')
    )
    op.create_table('picks',
    sa.Column('pick_id', sa.Uuid(), nullable=False),
    sa.Column('match_id', sa.Uuid(), nullable=False),
    sa.Column('sportsbook_id', sa.Uuid(), nullable=False),
    sa.Column('run_date', sa.Date(), nullable=False),
    sa.Column('market', sa.String(length=50), nullable=False),
    sa.Column('selection', sa.String(length=200), nullable=False),
    sa.Column('odds_american', sa.Integer(), nullable=False),
    sa.Column('odds_decimal', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('implied_prob', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('grade', sa.Enum('A', 'B', 'C', name='pick_grade'), nullable=False),
    sa.Column('stake', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('status', sa.Enum('pending', 'won', 'lost', 'push', 'void', name='pick_status'), nullable=False),
    sa.Column('source', sa.Enum('manual', 'pipeline', name='pick_source'), nullable=False),
    sa.Column('closing_odds_decimal', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('clv', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.match_id'], ),
    sa.ForeignKeyConstraint(['sportsbook_id'], ['sportsbooks.sportsbook_id'], ),
    sa.PrimaryKeyConstraint('pick_id')
    )
    op.create_table('parlay_picks',
    sa.Column('parlay_pick_id', sa.Uuid(), nullable=False),
    sa.Column('parlay_id', sa.Uuid(), nullable=False),
    sa.Column('pick_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parlay_id'], ['parlays.parlay_id'], ),
    sa.ForeignKeyConstraint(['pick_id'], ['picks.pick_id'], ),
    sa.PrimaryKeyConstraint('parlay_pick_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('parlay_picks')
    op.drop_table('picks')
    op.drop_table('matches')
    op.drop_table('parlays')
    op.drop_table('competitions')
    op.drop_table('sportsbooks')
    op.drop_table('sports')
    op.drop_table('config')
    # ### end Alembic commands ###
